import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <main className="flex-1">{children}</main>
          <footer className="border-t bg-neutral-100 py-6 text-sm text-neutral-600 dark:bg-neutral-900 dark:text-neutral-300">
            <div className="container mx-auto px-4 text-center">
              <p className="font-medium text-neutral-800 dark:text-neutral-100">
                MonkMonkeyKey
              </p>
              <p>© {new Date().getFullYear()} All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
